config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :projects do
    resources :projectlogs
  end

end

app/models/projectlog.rb
class Projectlog < ActiveRecord::Base
  belongs_to:project
end

app/controllers/projectlogs_controller.rb
class ProjectlogsController < ApplicationController
  before_action :set_projectlog, only: [:show, :edit, :update, :destroy]

  # GET /projectlogs
  # GET /projectlogs.json
  def index
    #@projectlogs = Projectlog.all
    @project = Project.find(params[:project_id])
    puts "-------------------------------" + @project.to_json
    @projectlogs = Projectlog.where('project_id=?', params[:project_id]).all
    #@projectlogs = Projectlog.find_by_sql("select l.* from projectlog l where l.project_id = "+params[:project_id])　

  end

  # GET /projectlogs/1
  # GET /projectlogs/1.json
  def show
  end

  # GET /projectlogs/new
  def new
    @projectlog = Projectlog.new
  end

  # GET /projectlogs/1/edit
  def edit
  end

  # POST /projectlogs
  # POST /projectlogs.json
  def create
    @projectlog = Projectlog.new(projectlog_params)

    respond_to do |format|
      if @projectlog.save
        format.html { redirect_to @projectlog, notice: 'Projectlog was successfully created.' }
        format.json { render :show, status: :created, location: @projectlog }
      else
        format.html { render :new }
        format.json { render json: @projectlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projectlogs/1
  # PATCH/PUT /projectlogs/1.json
  def update
    respond_to do |format|
      if @projectlog.update(projectlog_params)
        format.html { redirect_to @projectlog, notice: 'Projectlog was successfully updated.' }
        format.json { render :show, status: :ok, location: @projectlog }
      else
        format.html { render :edit }
        format.json { render json: @projectlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projectlogs/1
  # DELETE /projectlogs/1.json
  def destroy
    @projectlog.destroy
    respond_to do |format|
      format.html { redirect_to projectlogs_url, notice: 'Projectlog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projectlog
      @projectlog = Projectlog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def projectlog_params
      params.require(:projectlog).permit(:action, :actiondata, :username)
    end
end

app/helpers/projectlogs_helper.rb
module ProjectlogsHelper
end

app/views/projectlogs/_form.html.erb
<%= form_for(@projectlog) do |f| %>
  <% if @projectlog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@projectlog.errors.count, "error") %> prohibited this projectlog from being saved:</h2>

      <ul>
      <% @projectlog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :action %><br>
    <%= f.text_field :action %>
  </div>
  <div class="field">
    <%= f.label :actiondata %><br>
    <%= f.text_area :actiondata %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projectlogs/edit.html.erb
<h1>Editing projectlog</h1>

<%= render 'form' %>

<%= link_to 'Show', @projectlog %> |
<%= link_to 'Back', projectlogs_path %>

app/views/projectlogs/index.html.erb
<h1>Listing projectlogs</h1>

<table>
  <thead>
    <tr>
      <th>projectname</th>
      <th>Action</th>
      <th>Actiondata</th>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projectlogs.each do |projectlog| %>
      <tr>
        <td><%= @project[:projectname] %></td>
        <td><%= projectlog.action %></td>
        <td><%= projectlog.actiondata %></td>
        <td><%= projectlog.username %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Back', projects_path %>
<br>

app/views/projectlogs/new.html.erb
<h1>New projectlog</h1>

<%= render 'form' %>

<%= link_to 'Back', projectlogs_path %>

app/views/projectlogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Action:</strong>
  <%= @projectlog.action %>
</p>

<p>
  <strong>Actiondata:</strong>
  <%= @projectlog.actiondata %>
</p>

<p>
  <strong>Username:</strong>
  <%= @projectlog.username %>
</p>

<%= link_to 'Edit', edit_projectlog_path(@projectlog) %> |
<%= link_to 'Back', projectlogs_path %>